### ISSUE TITLE
Publish on rubygems

### ISSUE THREAD

**Issue by StefSchenkelaars** [nerab/i2c-ss1602#1]
Recently I found this gem which is really simple but it perfectly did the job. Since it is not on rubygems I now copied the `lib/i2c/drivers/ss1602/display.rb` to my own project but it would be better if it could be moved to my gemfile. It looks like everything is setup for a release of version `0.0.1`. So the question is if you can push it to rubygems.

**Comment by nerab** [comment]
Good to hear that it's useful. I'll look into publishing it.

**Comment by nerab** [comment]
It's [out now](https://rubygems.org/gems/i2c-ss1602).

**Comment by StefSchenkelaars** [comment]
👍
